name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
      - name: debug
        run: ls -a
      - name: debug build folder
        run: ls -a ./build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
